eatwell/urls.py
from django.urls import path
from eatwell import views

urlpatterns = [
    path('index/', views.index, name='index'),

    path('menu_add/', views.menu_add, name='menu_add'),
    path('menus/', views.menus, name='menus'),
    path('pay/', views.pay, name='pay'),
    path('register/', views.register, name='register'),
    path('showuser/', views.showuser, name='showuser'),
    path('loginx/', views.loginx, name='loginx'),
    path('restaurants/', views.restaurants, name='restaurants'),
    path('orders/', views.orders, name='orders'),

    # 添加餐馆
    path('restaurant_add/', views.restaurant_add, name='restaurant_add'),
    path('logoutx/', views.logoutx, name='logoutx'),

]

myorder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eatwell/', include(('eatwell.urls', 'eatwell'), namespace='eatwell')),
]

eatwell/models.py
from django.db import models
from django.contrib.auth.models import User
import json


class Restaurant(models.Model):
    name = models.CharField(max_length=255)
    address = models.TextField()

    def __str__(self):
        return self.name


# Create your models here.
class Menu(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE,default=1)

    def __str__(self):
        return self.name

    class Meta:
        pass


class Order(models.Model):
    STATUS = [
        ('1', '正在下单'),
        ('2', '已下单,待接单'),
        ('3', '已接单,待结单'),
        ('4', '结单'),
    ]
    orderid = models.CharField(max_length=10)
    goods = models.CharField(max_length=255, default='{}')
    status = models.CharField(max_length=1, choices=STATUS, default='1')
    created_time = models.DateTimeField(auto_now_add=True)

    def get_totalcount(self):
        # 第一步,根据goods 字符串,还原订单 菜品详情
        goods = json.loads(self.goods)  # [{1:2}]
        # for k,v in goods:
        mysum = 0
        for cai_id, cai_count in goods:
            mysum += cai_count * Menu.objects.get(id=cai_id).price
        return mysum


# 学生 外卖小哥 信息拓展表
class UserProfile(models.Model):
    JOBS = [('1', "学生"), ('2', '外卖小哥')]
    home_address = models.TextField(null=True, default='')
    phone = models.CharField(max_length=11)
    job = models.CharField(max_length=1, choices=JOBS)
    # user = models.ForeignKey(User, unique=True,on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

eatwell/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Menu, Order
from .models import UserProfile
from .models import Restaurant
import time
import json


# Create your views here.
def index(request):
    return render(request, 'index.html')


def menu_add(request):
    if request.method == "GET":
        restaurants = Restaurant.objects.all()
        return render(request, 'menu_add.html', {"restaurants": restaurants})
    if request.method == "POST":
        name = request.POST.get("name", "")
        price = request.POST.get("price", "0")
        restaurant = request.POST.get("restaurant", "0")
        try:
            price = float(price)
        except:
            print('菜品价格输入格式不对')
            return HttpResponse("菜品价格输入格式不对")
        Menu.objects.create(name=name, price=price, restaurant_id=restaurant)
        return redirect('eatwell:index')


def menus(request):
    rid = request.GET.get('rid')  # 根据rid 判断是哪个餐馆

    menus = Menu.objects.filter(restaurant_id=rid).all()
    id = request.GET.get('id', '')  # 如果id,说明我在点餐
    # 查询订单数据库

    try:
        order = Order.objects.get(status='1')  # 获取状态
        print('继续点餐')
        # 获取到 goods
        goods = order.goods
        goods = json.loads(goods)
        if id:
            if id in goods:  # 曾经点过这种菜品
                goods[id] += 1
            else:
                goods[id] = 1
            # 将本次的改变也写入到数据库
            order.goods = json.dumps(goods)
            order.save()
    except:
        print('-----------异常了----------------')
        if id:
            orderid = str(int(time.time()))
            order = Order.objects.create(orderid=orderid, goods=json.dumps({id: 1}))

            print(order.goods)  # {'2': 1}
            print(type(order.goods))
            goods = json.loads(order.goods)
            print(goods)
        else:
            goods = {}
    res = Menu.objects.all()
    ids = []
    names = []
    for m in res.values('id'):
        ids.append(m.get('id'))
    for n in res.values('name'):
        names.append(n.get('name'))

    print(ids)
    print(names)
    kv = {str(x): y for x, y in zip(ids, names)}
    print(kv)

    # res 是个三元组  (菜品名称,菜品id,菜品数量)
    res = []
    total = 0  # 总付款数
    # 遍历订单中所有 菜品
    # 每个菜品* 数量  加在一起
    # todo
    for cai_id, cai_count in goods.items():  #
        res.append((kv.get(cai_id), cai_id, cai_count))
        total += Menu.objects.get(id=cai_id).price * cai_count

    return render(request, 'menus.html', {"menus": menus, "goods": res, "total": total})


def pay(request):
    order = Order.objects.get(status='1')
    order.status = '2'
    order.save()
    return HttpResponse('下单完成!')


def register(request):
    if request.method == "GET":
        return render(request, 'register.html')

    if request.method == "POST":
        username = request.POST.get("username")
        home_address = request.POST.get("home_address")
        phone = request.POST.get("phone")
        password = request.POST.get("password")
        jobs = request.POST.get("jobs")

        # 创建用户
        user = User.objects.create_user(username=username, password=password)
        print(type(user.id))
        print(type(user.username))
        userprofile = UserProfile(home_address=home_address, phone=phone, job=jobs, user_id=user.id)
        userprofile.save()

        return HttpResponse("注册成功")


def showuser(request):
    userid = request.GET.get('id', '')
    if not userid:
        return HttpResponse("没有id参数")

    user = User.objects.get(id=int(userid))
    print(user.username)
    # print(type(user.userprofile_set.all()))
    # phone =user.userprofile_set.all().first().phone
    phone = user.userprofile.phone
    print(phone, 'home')
    # todo 展示用户信息,更改用户信息界面  job字段不可以更改
    # return render(request,'showuser.html',{"user":user})
    return HttpResponse('展示用户信息')


def loginx(request):
    if request.method == "GET":
        return render(request, 'loginx.html')
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        print(username, password, '------->')

        user = authenticate(username=username, password=password)
        if user.username:  # 判断一下有这个用户
            login(request=request, user=user)
            job = user.userprofile.job  # 用户身份
            # 不同身份跳转不同界面
            if job == '1':
                return redirect('eatwell:restaurants')
            elif job == '2':
                return redirect('eatwell:orders')
            else:
                return HttpResponse('登录成功')
        else:
            return HttpResponse('认证失败')
    return HttpResponse('请求方式有问题')


def restaurants(request):
    restaurant_objs = Restaurant.objects.all()
    return render(request, 'restaurants.html', {"restaurant_objs": restaurant_objs})


@login_required
def orders(request):
    if request.user.userprofile.job=='2':
        order_objs = Order.objects.all()
        return render(request,'orders.html',{"order_objs":order_objs})
    else:
        return HttpResponse('没有权限查看')

def restaurant_add(request):
    if request.method == "GET":
        return render(request, 'restaurant_add.html')
    if request.method == "POST":
        name = request.POST.get("name", "")
        address = request.POST.get("address", "")

        if name and address:
            Restaurant.objects.create(name=name, address=address)
            return redirect('eatwell:index')
        else:
            return redirect('eatwell:restaurant_add')


def logoutx(request):
    logout(request)
    return redirect('eatwell:index')

# todo 抢单

eatwell/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页功能页</title>
</head>
<body>

<a href="{% url 'eatwell:restaurant_add' %}">新建餐馆</a>
<br>
 <a href="{% url 'eatwell:restaurants' %}">展示所有餐馆</a>
<br>
<a href="{% url 'eatwell:menu_add' %}">添加菜品</a>
<br>
 <a href="{% url 'eatwell:menus' %}">展示菜品</a>
<br>
 <a href="{% url 'eatwell:logoutx' %}">注销登录</a>
<br>
 <a href="{% url 'eatwell:loginx' %}">登录</a>
<br>

</body>
</html>

eatwell/templates/loginx.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    用户名:<input type="text" name="username">
    <br>
    密码: <input type="password" name="password">

    <br>
    <input type="submit" value="登录">
</form>

<a href="{% url 'eatwell:register' %}">注册</a>
</body>
</html>

eatwell/templates/menu_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>menu_add</title>
</head>
<body>
<h1>菜品添加界面</h1>
<form action="" method="post">
    {% csrf_token %}
    菜品名:<input type="text" name="name">
    <br>
    菜品价格: <input type="text" name="price">
    <br>
    餐馆名称: <select name="restaurant" id="restaurant">
    {% for restaurant in restaurants %}
        <option value="{{ restaurant.id }}">{{ restaurant.name }}</option>
    {% endfor %}

</select>

    <input type="submit" value="提交">
</form>

</body>
</html>

eatwell/templates/menus.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>menus</title>
</head>
<body>
{% for menu in menus %}
    {{ menu.name }}--{{ menu.price }}  <a href="{% url 'eatwell:menus' %}?rid={{ menu.restaurant.id }}&id={{ menu.id }}">点餐</a>
    <br>
{% endfor %}


<h2>订单详情</h2>
{#菜品名称 &nbsp;&nbsp; 菜品价格&nbsp;&nbsp; 菜品数量#}
菜品名称&nbsp;&nbsp;菜品id &nbsp;&nbsp; 菜品数量
<br>
{% for cai_name,cai_id,cai_count in goods %}

    {{ cai_name }} &nbsp;&nbsp;{{ cai_id }} &nbsp;&nbsp; {{ cai_count }}
    <br>
{% endfor %}

总价:{{ total }} &nbsp;&nbsp;&nbsp; <a href="{% url 'eatwell:pay' %}">下单</a>

</body>
</html>

eatwell/templates/orders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>orders</title>
</head>
<body>
{% for order in order_objs %}
    {{ order.orderid }}--> <a href="">抢单</a>
    <br>
{% endfor %}

</body>
</html>

eatwell/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    用户名: <input type="text" name="username">
    <br>
    送餐地址: <textarea name="home_address" id="home_address" cols="30" rows="10"></textarea>
    <br>
    手机号码: <input type="text" name="phone">
    <br>
    密码: <input type="password" name="password">
    <br>

    身份选择: <select name="jobs" id="jobs">
    <option value="1">学生</option>
    <option value="2">外卖小哥</option>
</select>

    <br>
    <input type="submit" value="注册">
</form>

</body>
</html>

eatwell/templates/restaurant_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>restaurant_add</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    餐馆名称: <input type="text" name="name">
    <br>
    餐馆地址: <textarea name="address" id="address" cols="30" rows="10"></textarea>
    <input type="submit" value="提交">
</form>
</body>
</html>

eatwell/templates/restaurants.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>restaurants</title>
</head>
<body>
{% for restaurantin in restaurant_objs %}
    <h3>{{ restaurantin.name }} <a href="{% url 'eatwell:menus' %}?rid={{ restaurantin.id }}">进入点餐</a></h3>
{% endfor %}

</body>
</html>